#!/bin/bash

[ "$EUID" -eq 0 ] || exec sudo bash "$0" "$@"

puppet_dir=$(dirname $(readlink -f $(dirname $0)))

function install_puppet {
  if which apt-get &>/dev/null ; then
      apt-get update
      apt-get install puppet
  elif which pacman &>/dev/null ; then
      pacman -Sy
      pacman -S puppet
  fi
}

function edit_node_data {
  node_data=$puppet_dir/hieradata/node/$(facter fqdn).yaml

  if [ ! -f $node_data ]; then
      cp $puppet_dir/templates/node-data.yaml $node_data
  fi

  vi $node_data
}

function bootstrap {
    install_puppet
    edit_node_data
    # apply
}

function apply {
  puppet apply --confdir=$puppet_dir/puppet $puppet_dir/code/default.pp
}

case $1 in
    bootstrap|b)
        bootstrap
        ;;
    apply|a)
        apply
        ;;
    edit_node_data|e)
        edit_node_data
        ;;
    *)
        echo "Unknown command: $1"
        exit 1
        ;;
esac
